# Generated by Django 4.1 on 2022-08-10 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoreDataUser',
            new_name='MasDatosUsuario',
        ),
    ]
