# Generated by Django 4.1 on 2022-08-10 19:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('trama', ckeditor.fields.RichTextField(null=True)),
                ('fecha_estreno', models.DateField(auto_now_add=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('director', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
